#!/usr/bin/ksh
if [ "$(cat /sys/class/power_supply/BAT1/status)" = "Discharging"  ];then
	cat /sys/class/power_supply/BAT1/capacity

elif [ "$(cat /sys/class/power_supply/BAT0/status)" = "Discharging"  ];then
	cat /sys/class/power_supply/BAT0/capacity

elif [ "$(cat /sys/class/power_supply/BAT1/status)" = "Charging"  ];then
	cat /sys/class/power_supply/BAT1/capacity

elif [ "$(cat /sys/class/power_supply/BAT0/status)" = "Charging"  ];then
	cat /sys/class/power_supply/BAT0/capacity
fi
