#!/usr/bin/ksh

## honestly idk if all of these checks for bat1 are redundant since my system works without them so i might 
#  just get rid of them later


#if [ -e "/sys/class/power_supply/BAT1"  ]; then

	if [ "$(cat /sys/class/power_supply/BAT1/status)" = "Discharging"  ];then
		echo "bat1:$(cat /sys/class/power_supply/BAT1/capacity)"

	elif [ "$(cat /sys/class/power_supply/BAT0/status)" = "Discharging"  ];then
		echo "bat0:$(cat /sys/class/power_supply/BAT0/capacity)"

	elif [ "$(cat /sys/class/power_supply/BAT1/status)" = "Charging"  ];then
		echo "AC/bat1:$(cat /sys/class/power_supply/BAT1/capacity)"

	elif [ "$(cat /sys/class/power_supply/BAT0/status)" = "Charging"  ];then
		echo "AC/bat0:$(cat /sys/class/power_supply/BAT0/capacity)"
	fi
#fi
