#!/usr/bin/env sh

if [ -e /sbin/ip ]; then
	break
else
	echo 'command ip not found, please install iproute2 or a package that provides ip'
	echo 'if the ifconfig binary is installed, use ipaddr-ifconfig instead'
	exit
fi

if [ -z "$__dev" ]; then
	__devices="virt0 proton0 eth0 enp0s31f6 wlan0 wlp3s0"
	for __tested in $__devices; do
		if [ "$(cat /sys/class/net/$__tested/operstate)" = "up" ]; then
			__dev=$__tested	
			break
		fi
	done
fi 2> /dev/null

echo "$__dev/$(ip -4 ad show "$__dev" | awk -F ' *|:' '/inet/{sub(/\/.*/,"",$3);print $3}' | head -n 1)"
