#!/usr/bin/env sh
FREQ="$(awk '/MHz/{ temp+=$4; n++ } END{ printf("%f\n", temp/n) }' /proc/cpuinfo | awk '{ sub(".[^.]*$", ""); print }')"
TEMP="$(sensors coretemp-isa-0000 | awk '/Pack/{print int($2)}')"
LDAVG="$(cat /proc/loadavg | awk '{print ($2)}')"
MEM="$(~/.scripts/statusbar/memoryused)"

echo "$FREQ"MHz/"$TEMP"°C/"$LDAVG"/"$MEM"
